packagesPacman=(
    "hyprland"
    "hyprpaper"
    "hyprlock"
    "hypridle"
    "xdg-desktop-portal-hyprland"
    "waybar"
    "grim"
    "slurp"
    "cliphist"
);

packagesYay=(
    "wlogout"
    "nwg-look"
    "hyprshade"
    "waypaper"
    "mission-center"
    "grimblast-git"
    "bun-bin"
    "aylurs-gtk-shell"
);
